"""slice 9 settlements

Revision ID: 5674c11d33cc
Revises: 69c2b0dc2e9d
Create Date: 2026-07-07 12:58:24.215754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5674c11d33cc'
down_revision: Union[str, None] = '69c2b0dc2e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=False),
    sa.Column('to_user', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_by_action_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index('ix_settlements_created_by_action', ['created_by_action_id'], unique=False)
        batch_op.create_index('ix_settlements_ledger_deleted_created', ['ledger_id', 'deleted_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index('ix_settlements_ledger_deleted_created')
        batch_op.drop_index('ix_settlements_created_by_action')

    op.drop_table('settlements')
    # ### end Alembic commands ###
