"""slice 12 pending_intents

Revision ID: 574bcef09bb9
Revises: 27325f1f9957
Create Date: 2026-07-07 18:46:25.251381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '574bcef09bb9'
down_revision: Union[str, None] = '27325f1f9957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('proposer_user_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('intent_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['proposer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_intents', schema=None) as batch_op:
        batch_op.create_index('ix_pending_intents_chat_message', ['chat_id', 'message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_intents', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_intents_chat_message')

    op.drop_table('pending_intents')
    # ### end Alembic commands ###
