"""slice 2: expenses, expense_splits, actions

Revision ID: 69c2b0dc2e9d
Revises: add6cdca2804
Create Date: 2026-07-02 21:23:53.661461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69c2b0dc2e9d'
down_revision: Union[str, None] = 'add6cdca2804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('intent_json', sa.JSON(), nullable=False),
    sa.Column('before_image', sa.JSON(), nullable=True),
    sa.Column('result_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('result_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('undone_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['undone_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index('ix_actions_ledger_undone', ['ledger_id', 'undone_at'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('occurred_on', sa.String(), nullable=True),
    sa.Column('split_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_action_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expenses_created_by_action', ['created_by_action_id'], unique=False)
        batch_op.create_index('ix_expenses_ledger_deleted', ['ledger_id', 'deleted_at'], unique=False)

    op.create_table('expense_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owed_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_by_action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_splits', schema=None) as batch_op:
        batch_op.create_index('ix_expense_splits_expense_user', ['expense_id', 'user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_splits', schema=None) as batch_op:
        batch_op.drop_index('ix_expense_splits_expense_user')

    op.drop_table('expense_splits')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_ledger_deleted')
        batch_op.drop_index('ix_expenses_created_by_action')

    op.drop_table('expenses')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_ledger_undone')

    op.drop_table('actions')
    # ### end Alembic commands ###
