"""slice 1: users, identities, groups, group_members, ledgers, processed_updates

Revision ID: add6cdca2804
Revises: 
Create Date: 2026-07-02 15:53:16.872490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'add6cdca2804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('home_currency', sa.String(length=3), nullable=True),
    sa.Column('active_ledger_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_platform_chat_id'), ['platform_chat_id'], unique=True)

    op.create_table('processed_updates',
    sa.Column('update_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index('ix_group_members_group_user', ['group_id', 'user_id'], unique=True)

    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.create_index('ix_identities_platform_user', ['platform', 'platform_user_id'], unique=True)
        batch_op.create_index('ix_identities_platform_username', ['platform', 'username'], unique=False)
        batch_op.create_index(batch_op.f('ix_identities_user_id'), ['user_id'], unique=False)

    op.create_table('ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('logging_currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('board_message_id', sa.BigInteger(), nullable=True),
    sa.Column('board_chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.create_index('ix_ledgers_board_chat_message', ['board_chat_id', 'board_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ledgers_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledgers_group_id'))
        batch_op.drop_index('ix_ledgers_board_chat_message')

    op.drop_table('ledgers')
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identities_user_id'))
        batch_op.drop_index('ix_identities_platform_username')
        batch_op.drop_index('ix_identities_platform_user')

    op.drop_table('identities')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index('ix_group_members_group_user')

    op.drop_table('group_members')
    op.drop_table('users')
    op.drop_table('processed_updates')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_platform_chat_id'))

    op.drop_table('groups')
    # ### end Alembic commands ###
